# -*- coding: utf-8 -*-
"""postpredictions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tOUktdlOq1DjSQ0LTeZncYbEVtg2MaWp
"""

# Устанавливаем библиотеки
!pip install google-cloud-storage colarama pydantic=1.10.13 pydantic==1.10.9 instagrapi==1.16.27 threads_api==1.0.1

!pip install "pydantic<2.0"

import os
import json
import random
import time
from datetime import datetime
from google.cloud import storage
import requests

# === Настройки ===
PREDICTIONS_FILE = "postpredictions/predictions.json"
POSTED_FILE = "postpredictions/posted_today.json"
BUCKET = "thinarthrillbucket"  # без /postpredictions — это папка внутри bucket
WEBHOOK = "https://hook.eu2.make.com/35dyered8mobg4rk1p553u4zgzxpcdvf"


# === Преобразуем строку JSON в dict и исправляем переносы строк ===
def init_gcs_client():
    key_str = os.getenv("GCS_KEY_JSON")
    print(key_str)
    if not key_str:
        raise ValueError("❌ GCS_KEY_JSON не установлена или пуста")

    # Преобразуем строку из .env обратно в словарь
  key_dict = json.loads(key_str)

  # Сохраняем как файл
  with open("gcs_key.json", "w") as f:
      json.dump(key_dict, f)

  os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "gcs_key.json"
  return storage.Client()

# === Загрузка JSON из GCS ===
def gcs_load_json(bucket_name, gcs_path):
    client = init_gcs_client()
    bucket = client.get_bucket(bucket_name)
    blob = bucket.blob(gcs_path)

    if not blob.exists():
        print(f"⚠ Файл {gcs_path} не найден в bucket {bucket_name}")
        return None

    content = blob.download_as_text()
    try:
        data = json.loads(content)
    except json.JSONDecodeError:
        print(f"⚠ Ошибка декодирования JSON в {gcs_path}")
        return None

    print(f"📥 Загружено: {gcs_path}")
    return data

# === Сохранение JSON в GCS ===
def upload_to_gcs(bucket_name, gcs_filename, data):
    client = init_gcs_client()
    bucket = client.get_bucket(bucket_name)
    blob = bucket.blob(gcs_filename)
    blob.upload_from_string(
        json.dumps(data, ensure_ascii=False, indent=2),
        content_type="application/json"
    )
    print("📤 Файл загружен в GCS:", blob.public_url)
    return blob.public_url

# === Отправка текста в Make.com ===
def send_to_make(text):
    try:
        response = requests.post(WEBHOOK, json={"text": text})
        if response.status_code == 200:
            print(f"✅ Отправлено в Make: {text[:40]}...")
        else:
            print(f"⚠ Ошибка отправки в Make: {response.status_code}, {response.text}")
    except Exception as e:
        print(f"⚠ Ошибка HTTP-запроса: {e}")

def main():
    today = datetime.now().strftime("%Y-%m-%d")

    posted_today = gcs_load_json(BUCKET, POSTED_FILE)
    if not isinstance(posted_today, dict) or posted_today.get("date") != today:
        posted_today = {"date": today, "titles": []}

    predictions_data = gcs_load_json(BUCKET, PREDICTIONS_FILE)
    if not isinstance(predictions_data, list):
        print("⚠ Прогнозы не найдены, пропускаю...")
        return

    today_entry = next((day for day in predictions_data if day["date"] == today), None)
    if not today_entry:
        print(f"⚠ На сегодня ({today}) прогнозов нет, пропускаю...")
        return

    # Находим первый пост, который ещё не был опубликован
    post_to_publish = next(
        (post for post in today_entry["posts"] if post["title"] not in posted_today["titles"]),
        None
    )

    if not post_to_publish:
        print("✅ Все посты на сегодня уже опубликованы.")
        return

    # Публикуем
    send_to_make(post_to_publish["text"])
    posted_today["titles"].append(post_to_publish["title"])
    upload_to_gcs(BUCKET, POSTED_FILE, posted_today)
    print(f"✅ Опубликован пост: {post_to_publish['title']}")

if __name__ == "__main__":
    main()

from google.cloud import storage
import json

def gcs_load_json(filename):
    try:
        client = storage.Client.from_service_account_json("gcs_key.json")  # путь к ключу
        bucket = client.bucket(BUCKET)  # твой bucket
        blob = bucket.blob(filename)
        data = blob.download_as_text()
        return json.loads(data)
    except Exception as e:
        print(f"⚠ Ошибка загрузки {filename} из GCS: {e}")
        return None

gcs_load_json("predictions.json")

from google.cloud import storage

def gcs_debug(filename):
    try:
        client = storage.Client.from_service_account_json("gcs_key.json")
        bucket = client.bucket(BUCKET)
        blob = bucket.blob(filename)
        raw_data = blob.download_as_text()
        print("=== RAW DATA ===")
        print(raw_data[:500])  # первые 500 символов
        print("=== TYPE ===", type(raw_data))
    except Exception as e:
        print(f"Ошибка: {e}")

gcs_debug("posted_today.json")

